import { createThemeContract } from "@vanilla-extract/css";

export const tokens = createThemeContract({
  color: {
    primary: null,
    primaryContainer: null,
    secondary: null,
    secondaryContainer: null,
    tertiary: null,
    tertiaryContainer: null,
    surface: null,
    surfaceVariant: null,
    background: null,
    error: null,
    errorContainer: null,
    onPrimary: null,
    onPrimaryContainer: null,
    onSecondary: null,
    onSecondaryContainer: null,
    onTertiary: null,
    onTertiaryContainer: null,
    onSurface: null,
    onSurfaceVariant: null,
    onError: null,
    onErrorContainer: null,
    onBackground: null,
    outline: null,
    shadow: null,
    surfaceTint: null,
    inverseSurface: null,
    inverseOnSurface: null,
    inversePrimary: null,
  },
  state: {
    dragged: { overlay: { opacity: null } },
    pressed: { overlay: { opacity: null } },
    focus: { overlay: { opacity: null } },
    hover: { overlay: { opacity: null } },
    disabled: { content: { opacity: null }, container: { opacity: null } },
  },
  typescale: {},
  shape: {
    corner: {},
  },
  size: {
    outline: null,
  },
});
